openapi: 3.1.0
info:
  title: Kitchen API
  version: 1.0.0
  description: Kitchen API
servers:
  - url: https://{tenant}.api.kitchen.com
    variables:
      tenant:
        default: region-1
        description: Subdomain for the tenant
  - url: https://api.kitchen-dev.com
paths:
  /ingredients:
    post:
      tags:
        - ingredient
      operationId: createIngredient
      summary: Create ingredient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingredient'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - JWT: []
    get:
      tags:
        - ingredient
      operationId: getIngredients
      summary: Get ingredients
      responses:
        '200':
          description: A list of ingredients.
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    examples:
                      - list
                  page:
                    type: object
                    properties:
                      endCursor:
                        type: string
                        examples:
                          - ZG9uJ3QgZGVjb2RlIG1l
                      startCursor:
                        type: string
                        examples:
                          - ZG9uJ3QgZGVjb2RlIG1l
                      hasNextPage:
                        type: boolean
                        examples:
                          - false
                      hasPrevPage:
                        type: boolean
                        examples:
                          - false
                      limit:
                        type: integer
                        examples:
                          - 10
                      total:
                        type: integer
                        examples:
                          - 0
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ingredient'
                  total:
                    type: integer
                    examples:
                      - 1
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - JWT: []
  /ingredients/{ingredientId}:
    get:
      tags:
        - ingredient
      operationId: getIngredient
      summary: Get ingredient
      parameters:
        - name: ingredientId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of a specific ingredient.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - JWT: []
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    BadRequest:
      description: Bad request.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not found.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          readOnly: true
          type: string
          examples:
            - 497f6eca-6276-4993-bfeb-53cbbbba6f08
          format: uuid
        object:
          readOnly: true
          type: string
          examples:
            - ingredient
        kitchenId:
          type: string
          examples:
            - altman-family
        name:
          type: string
          examples:
            - broccoli
        quantity:
          type: number
          examples:
            - 1.5
        unit:
          type: string
          examples:
            - cups
        useBefore:
          type: string
          examples:
            - '2019-08-24T14:15:22Z'
          format: date-time
        createdAt:
          readOnly: true
          type: string
          examples:
            - '2019-08-24T14:15:22Z'
          format: date-time
      additionalProperties: false
      required:
        - kitchenId
        - name
    Error:
      type: object
      properties:
        type:
          type: string
          example: object
        title:
          type: string
          example: Error message
